---
title: "Tidyverse exercices"
format: html
editor: visual
---

# dplyr

## Série 1

-   Exercice 1 : Sélectionnez les colonnes "name" et "height" de starwars.

-   Exercice 2 : Filtrer les personnages dont l'espèce (species) est "Human".

-   Exercice 3 : Triez les personnages par leur taille (height) de la plus grande à la plus petite.

-   Exercice 4 : Créez une nouvelle colonne "bmi" (indice de masse corporelle) en utilisant les colonnes "weight" et "height". Le BMI se calcule comme weight / (height\^2).

-   Exercice 5 : Groupez les personnages par leur affiliation (affiliation) et calculez le nombre de personnages dans chaque groupe.

## Série 2

-   Exercice 6 : Sélectionnez les 5 premiers personnages dont l'âge (age) est supérieur à 30 ans.

-   Exercice 7 : Créez une colonne "homeworld_length" qui contient la longueur (nombre de caractères) du nom de la planète d'origine (homeworld).

-   Exercice 8 : Filtrez les personnages dont le nom de leur planète d'origine (homeworld) contient la lettre "o".

-   Exercice 9 : Calculez la taille moyenne (height) des personnages pour chaque espèce (species) et triez les résultats par taille moyenne décroissante.

-   Exercice 10 : Groupez les personnages par leur espèce (species) et calculez la taille moyenne (height) ainsi que la masse moyenne (weight) pour chaque espèce.

# ggplot2

# tidyr

# purrr

# stringr
